apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-price-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-price
  template:
    metadata:
      labels:
        app: flight-price
    spec:
      containers:
      - name: flight-price-container
        image: juliepriyanka/flight-price-app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: flight-price-service
spec:
  type: NodePort
  selector:
    app: flight-price
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30007
